//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Account", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group with the specified name already exists, please enter a different name..
        /// </summary>
        internal static string AddGroupStatus_GroupExists {
            get {
                return ResourceManager.GetString("AddGroupStatus_GroupExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum number of groups allowed under your current billing plan, you can upgrade using the page below..
        /// </summary>
        internal static string AddGroupStatus_PlanThresholdReached {
            get {
                return ResourceManager.GetString("AddGroupStatus_PlanThresholdReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address specified has been taken, please enter a different email address..
        /// </summary>
        internal static string AddOrganisationUserStatus_EmailExists {
            get {
                return ResourceManager.GetString("AddOrganisationUserStatus_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate your organisation..
        /// </summary>
        internal static string AddOrganisationUserStatus_InvalidOrganisation {
            get {
                return ResourceManager.GetString("AddOrganisationUserStatus_InvalidOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address supplied already exists in the system..
        /// </summary>
        internal static string AddUserStatus_EmailExists {
            get {
                return ResourceManager.GetString("AddUserStatus_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one group for this user..
        /// </summary>
        internal static string AddUserStatus_NoGroupsSelected {
            get {
                return ResourceManager.GetString("AddUserStatus_NoGroupsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum number of users allowed under your current billing plan, you can upgrade using the page below..
        /// </summary>
        internal static string AddUserStatus_PlanThresholdReached {
            get {
                return ResourceManager.GetString("AddUserStatus_PlanThresholdReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password..
        /// </summary>
        internal static string ConfirmPassword_Required {
            get {
                return ResourceManager.GetString("ConfirmPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organisation name specified has been taken, please enter a different name..
        /// </summary>
        internal static string CreateOrganisationStatus_OrganisationExists {
            get {
                return ResourceManager.GetString("CreateOrganisationStatus_OrganisationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address specified has been taken, please enter a different email address..
        /// </summary>
        internal static string CreateOrganisationStatus_UserExists {
            get {
                return ResourceManager.GetString("CreateOrganisationStatus_UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find the specified group to edit, please try again..
        /// </summary>
        internal static string DeleteGroupStatus_GroupNotFound {
            get {
                return ResourceManager.GetString("DeleteGroupStatus_GroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group has been deleted successfully..
        /// </summary>
        internal static string DeleteGroupStatus_Ok {
            get {
                return ResourceManager.GetString("DeleteGroupStatus_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently users in the group, please move these users to another group before deleting this group..
        /// </summary>
        internal static string DeleteGroupStatus_UsersInGroup {
            get {
                return ResourceManager.GetString("DeleteGroupStatus_UsersInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has been deleted successfully..
        /// </summary>
        internal static string DeleteUserStatus_Ok {
            get {
                return ResourceManager.GetString("DeleteUserStatus_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find the user to delete..
        /// </summary>
        internal static string DeleteUserStatus_UserNotFound {
            get {
                return ResourceManager.GetString("DeleteUserStatus_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find the specified group to edit, please try again..
        /// </summary>
        internal static string EditGroupStatus_GroupNotFound {
            get {
                return ResourceManager.GetString("EditGroupStatus_GroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email entered has already been taken, please enter a different email..
        /// </summary>
        internal static string EditUserStatus_EmailExists {
            get {
                return ResourceManager.GetString("EditUserStatus_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one group for this user..
        /// </summary>
        internal static string EditUserStatus_NoGroupsSelected {
            get {
                return ResourceManager.GetString("EditUserStatus_NoGroupsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details have been updated successfully..
        /// </summary>
        internal static string EditUserStatus_Ok {
            get {
                return ResourceManager.GetString("EditUserStatus_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find the user account to update..
        /// </summary>
        internal static string EditUserStatus_UserNotFound {
            get {
                return ResourceManager.GetString("EditUserStatus_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        internal static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address..
        /// </summary>
        internal static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your first name..
        /// </summary>
        internal static string FirstName_Required {
            get {
                return ResourceManager.GetString("FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a name for the group..
        /// </summary>
        internal static string GroupName_Required {
            get {
                return ResourceManager.GetString("GroupName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group has been updated successfully..
        /// </summary>
        internal static string Group_Updated {
            get {
                return ResourceManager.GetString("Group_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your last name..
        /// </summary>
        internal static string LastName_Required {
            get {
                return ResourceManager.GetString("LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for your organisation..
        /// </summary>
        internal static string Organisation_Required {
            get {
                return ResourceManager.GetString("Organisation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your passwords do not match, please re-type them..
        /// </summary>
        internal static string Password_Mismatch {
            get {
                return ResourceManager.GetString("Password_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password..
        /// </summary>
        internal static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
    }
}
