//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IssueResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IssueResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.IssueResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue was created successfully..
        /// </summary>
        internal static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned User.
        /// </summary>
        internal static string AssignedUser {
            get {
                return ResourceManager.GetString("AssignedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue with Id {0} was successfully deleted..
        /// </summary>
        internal static string DeleteIssueStatus_Ok {
            get {
                return ResourceManager.GetString("DeleteIssueStatus_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue details were updated successfully..
        /// </summary>
        internal static string DetailsUpdated {
            get {
                return ResourceManager.GetString("DetailsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Exceeded.
        /// </summary>
        internal static string ErrorLimitStatus_Exceeded {
            get {
                return ResourceManager.GetString("ErrorLimitStatus_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ErrorLimitStatus_Ok {
            get {
                return ResourceManager.GetString("ErrorLimitStatus_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearing Limit.
        /// </summary>
        internal static string ErrorLimitStatus_Warning {
            get {
                return ResourceManager.GetString("ErrorLimitStatus_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The errors associated with this issue have been queued for processing..
        /// </summary>
        internal static string IssueErrorsReceivedAgain {
            get {
                return ResourceManager.GetString("IssueErrorsReceivedAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string IssuePriority_High {
            get {
                return ResourceManager.GetString("IssuePriority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string IssuePriority_Low {
            get {
                return ResourceManager.GetString("IssuePriority_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string IssuePriority_Medium {
            get {
                return ResourceManager.GetString("IssuePriority_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very High.
        /// </summary>
        internal static string IssuePriority_VeryHigh {
            get {
                return ResourceManager.GetString("IssuePriority_VeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Low.
        /// </summary>
        internal static string IssuePriority_VeryLow {
            get {
                return ResourceManager.GetString("IssuePriority_VeryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The issue was successfully purged of errors..
        /// </summary>
        internal static string IssuePurged {
            get {
                return ResourceManager.GetString("IssuePurged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledged.
        /// </summary>
        internal static string IssueStatus_Acknowledged {
            get {
                return ResourceManager.GetString("IssueStatus_Acknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Deployment.
        /// </summary>
        internal static string IssueStatus_AwaitingDeployment {
            get {
                return ResourceManager.GetString("IssueStatus_AwaitingDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorable.
        /// </summary>
        internal static string IssueStatus_Ignorable {
            get {
                return ResourceManager.GetString("IssueStatus_Ignorable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Investigation.
        /// </summary>
        internal static string IssueStatus_Investigating {
            get {
                return ResourceManager.GetString("IssueStatus_Investigating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solved.
        /// </summary>
        internal static string IssueStatus_Solved {
            get {
                return ResourceManager.GetString("IssueStatus_Solved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unacknowledged.
        /// </summary>
        internal static string IssueStatus_Unacknowledged {
            get {
                return ResourceManager.GetString("IssueStatus_Unacknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate one of the issues to merge, merge failed..
        /// </summary>
        internal static string MergeIssuesStatus_IssueNotFound {
            get {
                return ResourceManager.GetString("MergeIssuesStatus_IssueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues were successfully merged..
        /// </summary>
        internal static string MergeIssuesStatus_Ok {
            get {
                return ResourceManager.GetString("MergeIssuesStatus_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rules for these two issues do not match therefore they cannot be merged..
        /// </summary>
        internal static string MergeIssuesStatus_RulesDoNotMatch {
            get {
                return ResourceManager.GetString("MergeIssuesStatus_RulesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for this issue..
        /// </summary>
        internal static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A background job has been queued to re-apply this issues rules to its application errors..
        /// </summary>
        internal static string ReapplyRulesJobQueued {
            get {
                return ResourceManager.GetString("ReapplyRulesJobQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original {0}.
        /// </summary>
        internal static string RulesAdjustmentOriginalIssuePrefix {
            get {
                return ResourceManager.GetString("RulesAdjustmentOriginalIssuePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An issue with these rules already exists &lt;a href=&apos;{0}&apos;&gt;click here to view&lt;/a&gt;..
        /// </summary>
        internal static string SameRulesExist {
            get {
                return ResourceManager.GetString("SameRulesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
    }
}
