//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Rules", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name.
        /// </summary>
        internal static string ErrorProperty_MachineName {
            get {
                return ResourceManager.GetString("ErrorProperty_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string ErrorProperty_Message {
            get {
                return ResourceManager.GetString("ErrorProperty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Name.
        /// </summary>
        internal static string ErrorProperty_MethodName {
            get {
                return ResourceManager.GetString("ErrorProperty_MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string ErrorProperty_Module {
            get {
                return ResourceManager.GetString("ErrorProperty_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a property..
        /// </summary>
        internal static string ErrorProperty_Required {
            get {
                return ResourceManager.GetString("ErrorProperty_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace.
        /// </summary>
        internal static string ErrorProperty_StackTrace {
            get {
                return ResourceManager.GetString("ErrorProperty_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Type.
        /// </summary>
        internal static string ErrorProperty_Type {
            get {
                return ResourceManager.GetString("ErrorProperty_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string ErrorProperty_Url {
            get {
                return ResourceManager.GetString("ErrorProperty_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agent.
        /// </summary>
        internal static string ErrorProperty_UserAgent {
            get {
                return ResourceManager.GetString("ErrorProperty_UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the new issue..
        /// </summary>
        internal static string IssueName_Required {
            get {
                return ResourceManager.GetString("IssueName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rules for this class have been adjusted successfully.  {0} errors have been attached as a consequence..
        /// </summary>
        internal static string RulesAdjusted {
            get {
                return ResourceManager.GetString("RulesAdjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new rules specified matched the current issue..
        /// </summary>
        internal static string RulesMatchedOtherIssue {
            get {
                return ResourceManager.GetString("RulesMatchedOtherIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string StringOperator_Contains {
            get {
                return ResourceManager.GetString("StringOperator_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does Not Contain.
        /// </summary>
        internal static string StringOperator_DoesNotContain {
            get {
                return ResourceManager.GetString("StringOperator_DoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does Not Equal.
        /// </summary>
        internal static string StringOperator_DoesNotEqual {
            get {
                return ResourceManager.GetString("StringOperator_DoesNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends With.
        /// </summary>
        internal static string StringOperator_EndsWith {
            get {
                return ResourceManager.GetString("StringOperator_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        internal static string StringOperator_Equals {
            get {
                return ResourceManager.GetString("StringOperator_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex Matches.
        /// </summary>
        internal static string StringOperator_RegexMatches {
            get {
                return ResourceManager.GetString("StringOperator_RegexMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts With.
        /// </summary>
        internal static string StringOperator_StartsWith {
            get {
                return ResourceManager.GetString("StringOperator_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for this rule..
        /// </summary>
        internal static string Value_Required {
            get {
                return ResourceManager.GetString("Value_Required", resourceCulture);
            }
        }
    }
}
