//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Errordite.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Errordite.Core.Resources.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job failed, error: {0}.
        /// </summary>
        public static string AsyncJobFailed {
            get {
                return ResourceManager.GetString("AsyncJobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job processed successfully, completed in {0}s {1}ms.
        /// </summary>
        public static string AsyncJobProcessed {
            get {
                return ResourceManager.GetString("AsyncJobProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Issue Rules.
        /// </summary>
        public static string AttachErrorsMessage {
            get {
                return ResourceManager.GetString("AttachErrorsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated {0} issues to {1} in {2}s {3}ms..
        /// </summary>
        public static string BulkStatusUpdateAuditMessage {
            get {
                return ResourceManager.GetString("BulkStatusUpdateAuditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Status Update.
        /// </summary>
        public static string BulkStatusUpdateMessage {
            get {
                return ResourceManager.GetString("BulkStatusUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Delete Issues.
        /// </summary>
        public static string DeleteIssuesMessage {
            get {
                return ResourceManager.GetString("DeleteIssuesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue was created by adjusting rules of issue with id {0} by {1} ({2})..
        /// </summary>
        public static string HistoryCreatedByRulesAdjustment {
            get {
                return ResourceManager.GetString("HistoryCreatedByRulesAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue was created by exception of type = {0}, method = {1}, module {2}, server = {3}.
        /// </summary>
        public static string HistoryIssueCreated {
            get {
                return ResourceManager.GetString("HistoryIssueCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue created by {0} ({1})..
        /// </summary>
        public static string HistoryIssueCreatedBy {
            get {
                return ResourceManager.GetString("HistoryIssueCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All errors associated with this issue were re-imported into the system, triggered by {0} ({1}).&lt;br /&gt;{2}.
        /// </summary>
        public static string HistoryIssueErrorsReceivedAgain {
            get {
                return ResourceManager.GetString("HistoryIssueErrorsReceivedAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The errors from issue with Id {0} ({1}) were merged into this issue as a result of a rules adjustment..
        /// </summary>
        public static string HIstoryIssueMerged {
            get {
                return ResourceManager.GetString("HIstoryIssueMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue was purged of all errors, job was triggered by {0} ({1}).
        ///.
        /// </summary>
        public static string HistoryIssuePurged {
            get {
                return ResourceManager.GetString("HistoryIssuePurged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status updated from {0} to {1} by {2} ({3})..
        /// </summary>
        public static string HistoryIssueStatusUpdated {
            get {
                return ResourceManager.GetString("HistoryIssueStatusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue details were updated by {0} ({1}), Status = {2}, Name = {3}, Always Notify = {4}..
        /// </summary>
        public static string HistoryIssueUpdated {
            get {
                return ResourceManager.GetString("HistoryIssueUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue rules were adjusted by {0} ({1}). New issue with Id {2} was created by this rules adjustment..
        /// </summary>
        public static string HistoryRulesAdjusted {
            get {
                return ResourceManager.GetString("HistoryRulesAdjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match on exception type and method name..
        /// </summary>
        public static string MethodAndTypeMatchRuleFactory_Description {
            get {
                return ResourceManager.GetString("MethodAndTypeMatchRuleFactory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception type and method name..
        /// </summary>
        public static string MethodAndTypeMatchRuleFactory_Name {
            get {
                return ResourceManager.GetString("MethodAndTypeMatchRuleFactory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match on exception type and module name..
        /// </summary>
        public static string ModuleAndTypeMatchRuleFactory_Description {
            get {
                return ResourceManager.GetString("ModuleAndTypeMatchRuleFactory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception type and module only..
        /// </summary>
        public static string ModuleAndTypeMatchRuleFactory_Name {
            get {
                return ResourceManager.GetString("ModuleAndTypeMatchRuleFactory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully purged {0} issues in {1}s {2}ms.
        /// </summary>
        public static string PurgedIssuesMessage {
            get {
                return ResourceManager.GetString("PurgedIssuesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge Errors.
        /// </summary>
        public static string PurgeErrorsMessage {
            get {
                return ResourceManager.GetString("PurgeErrorsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reapply Issue Rules.
        /// </summary>
        public static string ReapplyRulesMessage {
            get {
                return ResourceManager.GetString("ReapplyRulesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rules for this issue were reapplied to the system, {0} errors were added to this issue..
        /// </summary>
        public static string RulesReapplied {
            get {
                return ResourceManager.GetString("RulesReapplied", resourceCulture);
            }
        }
    }
}
