//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Errordite.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Errordite.Core.Resources.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new error has been received which matches &quot;always notify&quot; issue named {0}, &lt;a href=&quot;{1}/issue/{2}&quot;  target=&quot;_blank&quot;&gt;click here to view the issue&lt;/a&gt;..
        /// </summary>
        internal static string SimpleMessage_AlwaysNotifyIssueOccurance {
            get {
                return ResourceManager.GetString("SimpleMessage_AlwaysNotifyIssueOccurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The issue {0} is nearing its error threshold, Errordite will no longer record full error information for errors matching this issue, &lt;a href=&quot;{1}/issue/{2}&quot;  target=&quot;_blank&quot;&gt;click here to view the issue&lt;/a&gt;..
        /// </summary>
        internal static string SimpleMessage_ErrorThresholdReached {
            get {
                return ResourceManager.GetString("SimpleMessage_ErrorThresholdReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The issue {0} is nearing its error threshold. You should ensure the rules are appropriate for the errors being logged, &lt;a href=&quot;{1}/issue/{2}&quot;  target=&quot;_blank&quot;&gt;click here to view the issue&lt;/a&gt;..
        /// </summary>
        internal static string SimpleMessage_ErrorThresholdWarning {
            get {
                return ResourceManager.GetString("SimpleMessage_ErrorThresholdWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new issue has been created named {0}, &lt;a href=&quot;{1}/issue/{2}&quot;  target=&quot;_blank&quot;&gt;click here to view the issue&lt;/a&gt;..
        /// </summary>
        internal static string SimpleMessage_NewIssue {
            get {
                return ResourceManager.GetString("SimpleMessage_NewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: recurrence of solved issue &lt;a href=&quot;{1}/issue/{2}&quot;  target=&quot;_blank&quot;&gt;{3}&lt;/a&gt;..
        /// </summary>
        internal static string SimpleMessage_SolvedIssueOccurance {
            get {
                return ResourceManager.GetString("SimpleMessage_SolvedIssueOccurance", resourceCulture);
            }
        }
    }
}
